name: WebhookReport
version: '${version}'
main: dev.plastec.webhookreport.WebhookReport
api-version: '1.20'
commands:
  report:
    description: The main command for the WebhookReport plugin
    permission: webhookreport
permissions:
  webhookreport.bypasscooldown:
    description: Bypass report send command cooldown
  webhookreport.set:
    description: Allowed to make changes to the config using the /report set command
  webhookreport.set.webhook:
    description: Setting the webhook url
  webhookreport.set.cooldown:
    description: Setting the report send cooldown
  webhookreport.send:
    description: Sending a report via discord webhook
  webhookreport.status:
    description: Display plugin's status